apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  name: Mita
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine-app
  template:
    metadata:
      labels:
        app: alpine-app
    spec:
      containers:
      - name: alpine-container
        image: alpine
        command: ["/bin/sh", "-c", "while true; do echo $(NAME); sleep 5; done"]
        env:
        - name: NAME
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: name
