apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-empty-dir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shared-empty-dir
  template:
    metadata:
      labels:
        app: shared-empty-dir
    spec:
      containers:
        - name: container1
          image: alpine
          command: [ "sleep", "3600" ]
          volumeMounts:
            - mountPath: /shared
              name: empty-dir
        - name: container2
          image: alpine
          command: [ "sleep", "3600" ]
          volumeMounts:
            - mountPath: /shared
              name: empty-dir
        - name: container3
          image: alpine
          command: [ "sleep", "3600" ]
          volumeMounts:
            - mountPath: /shared
              name: empty-dir
      volumes:
        - name: empty-dir
          emptyDir: {}
